version: '3.3'
services:
  php:
    image: php:8.2.10-apache
    volumes:
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    command:
      - bash
      - -c
      - |
        chmod +x script.sh && \
        ./script.sh

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "ins"
      MYSQL_USER: "hector"
      MYSQL_PASSWORD: "123456"
    ports: 
      - "9999:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8090:80"
